import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout";
import Button from "../components/Button";
import Logo from "../components/Icons/Logo";
import { gitHubLogin, onAuthStateChanged } from "./firebase/client";

export default function Home() {
  const [user, setUser] = useState(null);
  console.log("USER IS ==> ", user);

  useEffect(() => {
    //onAuthStateChanged(setUser);
    console.log("*****", typeof onAuthStateChanged(setUser));

    // onAuthStateChanged(() => {})
  }, []);

  const handleClick = () => {
    gitHubLogin().then((user) => {
      const { avatar, userName, name } = user;
      setUser(user);
      console.log("USER IS ==> ", user);
    });
  };

  return (
    <>
      <Head>
        <title>Socially</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <main>
          <h1>Welcome to</h1>
          <Link href="/timeline">timeline</Link>
          {user === null && (
            <Button onClick={handleClick}>
              {" "}
              <Logo width={60} height={40} />
              Login
            </Button>
          )}
        </main>
      </AppLayout>
    </>
  );
}
